### ISSUE TITLE
Trail resets for factory-created game objects

### ISSUE THREAD

**Issue by Palisand** [indiesoftby/defold-hyper-trails#2]
I have a game object with the `trail_maker.script` and `trail_model`. Instances of this object are created via a factory. This results in what I can only describe as a reset for all objects created by the factory:

https://user-images.githubusercontent.com/4138177/132250077-f2ed7346-91aa-413f-962c-9c22c02dd3f2.mov

Notice how the trail behaves upon object creation. How can I prevent this reset from occurring?

**Comment by aglitchman** [comment]
> Instances of this object are created via a factory

Take a look at README:
> **Known Issues**
> For each trail in the collection, specify **a unique texture0** for the trail_model.

It means that Hyper Trails doesn't support being created via factory. The best you can do is:
- make a bunch of game objects with trails (object with trail_maker + unique trail_model + unique texture), for example, 10 of them.
- use it as a pool of trails, i.e. acquire + enable a trail, then release + disable when an object goes off-screen.

**Comment by Palisand** [comment]
That seems like a feasible and resource-efficient option. Thank you. I'll close this issue once I get something working.

**Comment by Palisand** [comment]
Alright, I got it working with your suggestions. In order to prevent the old trail position (captured when disabled) from affecting the new position (when enabled), I slightly altered the `trial_maker.script` so that it accepts a `"reset"` message that invokes `init_vars` and `init_data_points`.
